#��������Դ
spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/myproject?useUnicode=true&characterEncoding=utf8
     username: root
     password: 1234
     driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8082

#ע��xml�ϲ���
#ָ��mybatisӳ���ļ��ĵ�ַ
mybatis:
  mapper-locations: classpath:mapper/*.xml
